import { Link } from "react-router-dom";
import { ArrowRight, Lock, Mail, User } from "lucide-react";
import Navbar from "@/components/Navbar";

const AuthPage = ({ mode }: { mode: "login" | "register" }) => {
  const isRegister = mode === "register";
  return <div className="min-h-screen bg-[linear-gradient(135deg,#f8fbff,#eaf3ff)] text-slate-950"><Navbar /><main className="mx-auto grid max-w-6xl items-center gap-10 px-6 py-16 lg:grid-cols-2"><section><p className="font-bold uppercase tracking-widest text-blue-600">{isRegister ? "Create your account" : "Welcome back"}</p><h1 className="mt-4 text-4xl font-black md:text-6xl">{isRegister ? "Join the InternBridge community." : "Login to your opportunity hub."}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{isRegister ? "Build your student profile, save opportunities, and receive curated career and research resources." : "Continue tracking internships, research programs, partnerships, and professional growth resources."}</p></section><form className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-2xl shadow-blue-950/10"><div className="space-y-4">{isRegister && <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">Full name</span><div className="flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3"><User className="h-5 w-5 text-slate-400" /><input className="w-full outline-none" placeholder="Your name" /></div></label>}<label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">Email</span><div className="flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3"><Mail className="h-5 w-5 text-slate-400" /><input className="w-full outline-none" placeholder="student@example.com" /></div></label><label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">Password</span><div className="flex items-center gap-3 rounded-xl border border-slate-200 px-4 py-3"><Lock className="h-5 w-5 text-slate-400" /><input className="w-full outline-none" type="password" placeholder="••••••••" /></div></label></div><button type="button" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 font-bold text-white">{isRegister ? "Register" : "Login"}<ArrowRight className="h-4 w-4" /></button><p className="mt-5 text-center text-sm text-slate-600">{isRegister ? "Already have an account?" : "New to InternBridge?"} <Link className="font-bold text-blue-700" to={isRegister ? "/login" : "/register"}>{isRegister ? "Login" : "Register"}</Link></p></form></main></div>;
};
export default AuthPage;
